### ISSUE TITLE
adapt Code-Review Checklist to Isabelle

### ISSUE THREAD

**Issue by maxhaslbeck** [isabelle-prover/conventions#5]
https://github.com/kappelmann/isabelle_conventions/blob/master/pull_requests.md#code-review-checklist

is this already done?

**Comment by kappelmann** [comment]
I think it is fine the way it is - the checklist should just be a short reminder that there are standards to check when creating and reviewing a PR. I added a note that one should use it for this purpose here: https://github.com/kappelmann/isabelle_conventions/commit/142cbeb7eb5d220d5c21bd457c849e57ad9465ea
